### ISSUE TITLE
permanent, persistent and temporary modes

### ISSUE THREAD

**Issue by Zecat** [PolymerElements/paper-drawer-panel#121]
From the [spec](https://www.google.com/design/spec/patterns/navigation-drawer.html#navigation-drawer-behavior), the drawer can be
- permanent
  
  > Recommended default for desktop
- persistent #103 
  
  > Persistent navigation drawers are acceptable for all sizes larger than mobile.
- temporary
  
  > Recommended for:
  >    Tablet
  >    Required for:
  >    Mobile

So I propose some changes on attributes :
- replace "responsiveWidth" by "tabletWidth" and "mobileWidth"
- replace "narrow" by "mobile", "tablet" and "desktop"
- remove "forceNarrow"
- add "tabletMode" and "desktopMode" ( = "permanent" | "persistent" | "temporary")

**Comment by blasten** [comment]
hmm. I would recommend taking a look at app-layout, so you can see where we are going to. https://github.com/PolymerLabs/app-layout

We'd keep this into consideration for the API design of `app-drawer-layout`, but I believe the code to explicitly support these modes should belong to the application rather than the element itself. In that way, the API of the element remains granular and it can support more use cases/designs.

I've moved this issue to https://github.com/PolymerLabs/app-layout/issues/38
